server:
  port: 8990
spring:
  application:
    name: GATEWAY
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.150:8848
    gateway:
      routes:
        - id: service-Sentinal
          uri: http://10.10.197.42:8077
          predicates:
            - Path=/sen/getSentinalTop  #断言,路径相匹配的进行路由