server:
  port: 8077

spring:
  application:
    name: nanlistSentinel
  cloud:
    #向sentinel控制台注册服务
    sentinel:
      transport:
        dashboard: 192.168.8.144:8082
        #客户端端口号
        port: 8719
      #取消控制台懒加载
      eager: true